AllCops:
  Exclude:
    - 'tmp/**/*'
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.1.5
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace
Layout/EndOfLine:
  EnforcedStyle: lf
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
